from backend.database.aggregation_access.dma import DmaAggregationAccess
from backend.database.aggregation_access.site import SiteAggregationAccess
from backend.database.aggregation_access.time import TimeAggregationAccess
