"""indicies

Revision ID: 7f408fbb1179
Revises: 3761df14a877
Create Date: 2023-10-31 11:48:50.960944

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f408fbb1179"
down_revision: Union[str, None] = "3761df14a877"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_impression_uuid",
        "event",
        ["impression_uuid"],
        unique=False,
        postgresql_using="hash",
    )
    op.create_index(
        "idx_mm_dma", "impression", ["mm_dma"], unique=False, postgresql_using="btree"
    )
    op.create_index(
        "idx_site_id", "impression", ["site_id"], unique=False, postgresql_using="btree"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_site_id", table_name="impression", postgresql_using="btree")
    op.drop_index("idx_mm_dma", table_name="impression", postgresql_using="btree")
    op.drop_index("idx_impression_uuid", table_name="event", postgresql_using="hash")
    # ### end Alembic commands ###
