apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-api
  name: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicaCounts }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: {{ .Release.Name }}-api
          image: "{{ .Values.api.image.registry }}/{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.secret_name }}
            - configMapRef:
                name: {{ .Release.Name }}-env
          args:
            - gunicorn
            - -k
            - uvicorn.workers.UvicornWorker
            - -w
            - "{{ .Values.api.workers_count }}"
            - -b
            - ":{{ .Values.api.port }}"
            - backend.main:APP
            - --limit-request-line
            - "0"
            - --timeout
            - "180"
            - --log-level
            - "debug"
          ports:
            - containerPort: {{ .Values.api.port }}
          imagePullPolicy: Always
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "pidof -x gunicorn"
            periodSeconds: 1
            failureThreshold: 30
          livenessProbe:
            periodSeconds: 20
            failureThreshold: 3
            exec:
              command:
                - /bin/sh
                - -c
                - "pidof -x gunicorn"
      restartPolicy: Always
