apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate
  labels:
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-migrate
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}-migrate
        image: "{{ .Values.migrations.image.registry }}/{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
        resources:
          {{- toYaml .Values.migrations.resources | nindent 12 }}
        envFrom:
          - secretRef:
              name: {{ .Values.secrets.secret_name }}
          - configMapRef:
              name: {{ .Release.Name }}-env
        command: ["alembic"]
        args: ["upgrade", "head"]
  backoffLimit: 3
